/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

// #include "../../../../FrameWork/Core/OS/Architecture.hpp"
// #if defined(FLUX_ARCH_ARM_NEON)
// #define THORVG_NEON_VECTOR_SUPPORT 1
// #elif defined(FLUX_ARCH_INTEL)
// #define THORVG_AVX_VECTOR_SUPPORT 1
// #endif

#define THORVG_LOTTIE_LOADER_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT    1
#define THORVG_PNG_LOADER_SUPPORT    1
#define THORVG_JPG_LOADER_SUPPORT    1

#define THORVG_SW_RASTER_SUPPORT     1

#define THORVG_THREAD_SUPPORT        0

#define THORVG_TVG_LOADER_SUPPORT    1

#define THORVG_VERSION_STRING        "0.14.0"

#if 0
#    ifdef _DEBUG
#        define THORVG_LOG_ENABLED 1
#    endif// _DEBUG
#endif    //
